---
  - name: Create YUM repository (Fedora)
    yum_repository:
      name: "{{ yum_repo_name }}"
      description: "{{ yum_repo_description }}"
      baseurl: "{{ yum_repo_baseurl }}"
      gpgkey: "{{ code_repo_key }}"
      gpgcheck: yes
      enabled: yes

  - name: Install required package(s) (Fedora)
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - compat-openssl10

  - name: Install the application package (Fedora)
    package:
      name: "{{ package_name }}"
      state: present
